export interface defaultThemeInterface {
    yellowLight: string,
    yellow: string,
    yellowDark: string,
    purpleLight: string,
    purple: string,
    purpleDark: string,
    baseTitle: string,
    baseSubtTitle: string,
    baseText: string,
    baseLabel:string,
    baseHover: string,
    baseButton: string,
    baseInput: string,
    baseCard: string,
    background: string,
    white: string, 
}
export const defaultTheme: defaultThemeInterface = {
    yellowLight: '#F1E9C9',
    yellow: '#DBAC2C',
    yellowDark: '#C47F17',
    purpleLight: '#EBE5F9',
    purple: '#8047F8',
    purpleDark: '#4B2995',
    baseTitle: '#272221',
    baseSubtTitle: '#403937',
    baseText: '#574F4D',
    baseLabel:'#8D8686',
    baseHover: '#D7D5D5',
    baseButton: '#E6E5E5',
    baseInput: '#EDEDED',
    baseCard: '#F3F2F2',
    background: '#FAFAFA',
    white: '#FFFFFF', 
};